# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Jest Testing CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm ci
    - run: npm test -- --coverage
    - name: Upload coverage report
      uses: actions/upload-artifact@v3
      with:
        name: coverage-report
        path: coverage
    - name: Comment on pull request with coverage summary
      env:
        GH_TOKEN: ${{ github.token }}
      if: github.event_name == 'pull_request'
      run: |
        COVERAGE=$(npx jest --coverage --coverageReporters=text-summary | tail -n 10)
        COMMENT="### Jest Coverage Report\n\`\`\`\n$COVERAGE\n\`\`\`"
        gh pr comment ${{ github.event.pull_request.number }} --body "$COMMENT"
